base_channels: 32
base_ema: 0.99
batch_size: 28
crop_size: 96
data_dir: null
lr: 0.001
manifest: manifests/batch3_abeta_cortex_hipp_10k.json
max_steps: 890
method: simclr
num_input_channels: 1
num_levels: 5
num_workers: 16
optimizer_type: default
pred_hidden_dim: 4096
proj_hidden_dim: 4096
proj_output_dim: 256
warmup_steps: 89
weight_decay: 0.0001
